INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Português', 'Letras');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Espanhol', 'Letras');

INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Matemática', 'Ciências');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('História', 'Letras');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Geografia', 'Letras');

INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Química', 'Ciências');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Física', 'Ciências');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Biologia', 'Saúde');
INSERT INTO DISCIPLINA (TITULO, AREA) VALUES ('Computação', 'Tecnologia');


